version: '3.8'

services:
  fileregister:
    build : .
    command : uvicorn app.main:app --host 0.0.0.0 --port 80
    ports:
      - 80:80
    environment:
      - ENV_STATE=dev
    depends_on:
      db :
        condition: service_healthy
    

  db:
    image: postgres:13.0-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=microservices
    expose: 
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

